services:
  # PostgreSQL Database
  - type: pserv
    name: retronetwork-db
    runtime: postgresql15
    plan: free
    ipAllowList: [] # Allow all IPs
  
  # Web Service
  - type: web
    name: retronetwork  
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    region: frankfurt 
    plan: free  
    branch: main  
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true  
      - key: ALLOWED_HOSTS
        sync: false  
      - key: PYTHON_VERSION
        value: '3.12'
      - key: PORT
        value: '8000'
      - key: DATABASE_URL
        fromDatabase:
          name: retronetwork-db
          property: connectionString
    autoDeploy: true
    depends_on:
      - retronetwork-db
