services:
  - type: pserv
    name: retronetwork-db
    runtime: postgresql15
    plan: free
    region: frankfurt
  
  - type: web
    name: retronetwork
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    region: frankfurt
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: 'retronetwork.onrender.com'
    autoDeploy: true
    depends_on:
      - retronetwork-db
